services:
    rstudio:
        build:
            context: .
        environment:

            - DISABLE_AUTH=true

        volumes:
            - type: bind
              source: ./src
              target: /home/rstudio/src

            - type: bind
              source: renv
              target: /home/rstudio/.cache/R/renv

        tty: true
        stdin_open: true

volumes:
  renv:
    external: true

